### ISSUE TITLE
eeschema_do - Missing library

### ISSUE THREAD

**Issue by leoheck** [INTI-CMNB/kicad_ci_test#4]
Hi, it is me again. I hope I am not bothering you so much.

My eeschema_do is failing here. What do I need to do so it can find both the regular library and my custom library that is in the folder project? 

![image](https://user-images.githubusercontent.com/1277920/83319449-e8fa8800-a214-11ea-8c50-8ab8e14ca6b9.png)

Thank you for this whole ecosystem you are creating.

**Comment by set-soft** [comment]
Without access to your files I can only guess.
This message means that when we started KiCad it opened the dialog saying that some library is missing.
If your library is there double check what "sym-lib-table" says about the lib.
The library must be accesible on *any* machine, so you can't use absolute paths.
Here is an example from a project I have:
(sym_lib_table
  (lib (name esquematico)(type Legacy)(uri ${KIPRJMOD}/../lib/Esquematico.lib)(options "")(descr ""))
)
The environment variable KIPRJMOD expands to the directory containing you KiCad project. In this case the relative path to the library is "../lib/" and the library is "Esquematico.lib". All rereferences in the SCH will be "esquematico".
Using this kind of "tricks" is needed in order to share your KiCad project with other people, not just for CI/CD.
Let me know if this is your problem.

**Comment by leoheck** [comment]
`Good First Issue` :)

This is not an issue at all. It is fixed.

Since I could not initialize the submodule yet. I am downloading the library package inside the project folder. This step was good. But the library package was not well-formed.
