### ISSUE TITLE
Question - Jobs organization

### ISSUE THREAD

**Issue by leoheck** [INTI-CMNB/kicad_ci_test#6]
@set-soft Do you have any special reason to split the jobs the way you did? I mean, why not add ERC, DRC, and other steps in the same job? I am seeing here that the container is downloaded in every step. 

My guess is that you use that to create the dependency with the `needs` keyword. Am I right?

**Comment by set-soft** [comment]
There is no special reason. It was just a solution that came to my mind. The result is more modular allowing more flexibility, but is just a way to do it.

And yes I use it for dependencies. But steps also implies dependency. 

One important difference between jobs and steps is that jobs can be run in parallel. So you can run ERC and DRC in parallel. And then generate the files that passed the test. But you could want to generate the files even if the checks failed.

Separating them as jobs also makes more clear what you see in the actions, because you get information separated for ERC and DRC, look here:

[Actions page](https://github.com/INTI-CMNB/kicad_ci_test/actions/runs/83357293)

If you make both as part of one step, or just two steps you don't get clear information of what failed and you need to see the job log.
